name: "ZXC: Compile"
on:
  workflow_call:
#    secrets:
#      gradle-cache-username:
#        description: "The username used to authenticate with the Gradle Build Cache Node."
#        required: true
#      gradle-cache-password:
#        description: "The password used to authenticate with the Gradle Build Cache Node."
#        required: true

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.gradle-cache-username }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.gradle-cache-password }}

jobs:
  compile:
    name: Compile and Test
    runs-on: network-node-linux-medium
    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17.0.12

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          cache-read-only: false

      - name: Compile Code
        run: ./gradlew assemble --scan

      - name: Code Quality Checks and Tests
        run: ./gradlew check --scan

      - name: Publish JUnit Test Report
        with:
          check_name: JUnit Test Report
          time_unit: seconds
          junit_files: "build/test-results/**/*.xml"
